# Generated by Django 5.1.6 on 2025-12-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review_chat_history_image_review_guest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='chat_history_image',
        ),
        migrations.AddField(
            model_name='review',
            name='chat_history_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='chat_history_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
