# Generated by Django 5.1.6 on 2025-12-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_review_chat_history_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='chat_history_code',
        ),
        migrations.RemoveField(
            model_name='review',
            name='chat_history_session_id',
        ),
        migrations.AddField(
            model_name='review',
            name='chat_history_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
