# Generated by Django 5.1.1 on 2026-01-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_chatsession_session_id_and_more'),
    ]

    operations = [
    ]
