"""
تبدیل CIR -> نت‌لیست SPICE (به صورت دترمینیستیک، بدون AI).

هر نوع المان به یک خط نت‌لیست SPICE استاندارد نگاشت می‌شود.
نگاشت‌ها بر اساس قراردادهای ngspice/SPICE3 هستند.
"""

from __future__ import annotations

from core.cir import Circuit, Component, ComponentType
from core.interfaces.cir_to_spice import CIRToSpice

# پیشوند SPICE برای هر نوع المان (حرف اول نام المان در نت‌لیست)
SPICE_PREFIX: dict[ComponentType, str] = {
    ComponentType.RESISTOR: "R",
    ComponentType.CAPACITOR: "C",
    ComponentType.INDUCTOR: "L",
    ComponentType.VOLTAGE_SOURCE: "V",
    ComponentType.AC_VOLTAGE_SOURCE: "V",
    ComponentType.CURRENT_SOURCE: "I",
    ComponentType.DIODE: "D",
    ComponentType.BJT_NPN: "Q",
    ComponentType.BJT_PNP: "Q",
    ComponentType.MOSFET_N: "M",
    ComponentType.MOSFET_P: "M",
    ComponentType.JFET: "J",
    ComponentType.OPAMP: "X",
    ComponentType.IC: "X",
}

# مدل پیش‌فرض برای المان‌هایی که به مدل نیاز دارند ولی value ندارند
DEFAULT_MODEL: dict[ComponentType, str] = {
    ComponentType.DIODE: "D1N4148",
    ComponentType.BJT_NPN: "2N2222",
    ComponentType.BJT_PNP: "2N2907",
    ComponentType.MOSFET_N: "IRF530",
    ComponentType.MOSFET_P: "IRF9530",
    ComponentType.JFET: "J2N5457",
    ComponentType.OPAMP: "LM741",
}

# تعریف‌های .model داخلی برای مدل‌های پیش‌فرض — ngspice بدون اینها شبیه‌سازی نمی‌کند
BUILT_IN_MODELS: dict[str, str] = {
    "D1N4148": ".model D1N4148 D(Is=2.52n Rs=.568 N=1.752 Cjo=4p M=.4 tt=20n)",
    "2N2222":  ".model 2N2222 NPN(Bf=255 Vaf=74 Is=14.3f Ise=14.3f Ne=1.31 Ikf=.285 Xtb=1.5 Br=6.1 Nc=2 Isc=0 Ikr=0 Rc=1 Cjc=7.31p Mjc=.342 Vjc=.75 Fc=.5 Cje=22p Mje=.377 Vje=.75 Tf=411p Itf=.6 Vtf=1.7 Xtf=3 Rb=10)",
    "2N2907":  ".model 2N2907 PNP(Bf=235 Vaf=115 Is=14.3f Ise=14.3f Ne=1.3 Ikf=.285 Xtb=1.5 Br=6.1 Nc=2 Isc=0 Ikr=0 Rc=1 Cjc=14.6p Mjc=.345 Vjc=.75 Fc=.5 Cje=19.8p Mje=.38 Vje=.75 Tf=480p Itf=.6 Vtf=1.7 Xtf=3 Rb=10)",
    "IRF530":  ".model IRF530 NMOS(Vto=3.0 Kp=5.8 Gamma=0 Phi=0.6 Lambda=0)",
    "IRF9530": ".model IRF9530 PMOS(Vto=-3.0 Kp=5.8 Gamma=0 Phi=0.6 Lambda=0)",
    "J2N5457": ".model J2N5457 NJF(Beta=1.304m Rd=1 Rs=1 Cgs=4.06p Cgd=1.89p Pb=.6 Is=33.57f Vto=-2.5 Lambda=4m)",
}


class CIRToSpiceError(Exception):
    pass


class BasicCIRToSpice(CIRToSpice):
    """تبدیل ساده CIR به نت‌لیست SPICE.

    محدودیت‌های فعلی (برای نسخه‌های بعد):
    - opamp/IC به صورت subcircuit (X...) نوشته می‌شوند اما تعریف
      .subckt آن‌ها اضافه نمی‌شود؛ کاربر باید مدل را خود فراهم کند
      یا در آینده این بخش با کتابخانه مدل‌ها تکمیل شود.
    """

    def convert(self, circuit: Circuit) -> str:
        if not circuit.components:
            raise CIRToSpiceError("مدار خالی است؛ نمی‌توان نت‌لیست تولید کرد.")

        title = circuit.metadata.get("title", "Generated by ai-circuit-platform")
        lines: list[str] = [f".title {title}"]

        needed_models: set[str] = set()
        for comp in circuit.components:
            lines.append(self._component_line(comp))
            model = comp.value or DEFAULT_MODEL.get(comp.type, "")
            if model in BUILT_IN_MODELS:
                needed_models.add(model)

        for model_name in sorted(needed_models):
            lines.append(BUILT_IN_MODELS[model_name])

        lines.append(".end")
        return "\n".join(lines)

    def _component_line(self, comp: Component) -> str:
        prefix = SPICE_PREFIX.get(comp.type)
        if prefix is None:
            raise CIRToSpiceError(
                f"نوع المان '{comp.type.value}' در حال حاضر برای تبدیل به "
                f"SPICE پشتیبانی نمی‌شود."
            )

        # اگر id کاربر از قبل با پیشوند صحیح شروع شده، همان حفظ شود
        name = comp.id if comp.id.upper().startswith(prefix) else f"{prefix}{comp.id}"

        value_or_model = comp.value or DEFAULT_MODEL.get(comp.type, "")

        if not value_or_model:
            raise CIRToSpiceError(
                f"المان {comp.id} مقدار/مدل ندارد و مقدار پیش‌فرضی هم "
                f"برای نوع آن تعریف نشده است."
            )

        # برای MOSFET: اگر body/bulk داده نشده، به source وصل می‌شود (رایج‌ترین حالت)
        nodes = list(comp.nodes)
        if comp.type in (ComponentType.MOSFET_N, ComponentType.MOSFET_P) and len(nodes) == 3:
            nodes.append(nodes[2])  # bulk = source

        return f"{name} {' '.join(nodes)} {value_or_model}"
