# api_client.py
import os
import json
import requests
import re

# ------------------------------
# تنظیمات
# ------------------------------

PROMPT = """
You are an expert analog/digital circuit designer.
User will describe a circuit in natural language.
Respond ONLY with a JSON object:
{
  "spice": "...",
  "components": [...]
}
""".strip()

SYSTEM_PROMPT = (
    "شما یک تولیدکننده کد برای مدارهای الکتریکی هستید.\\n"
    "کاربر توضیح یک مدار الکتریکی را به شما می‌دهد و شما باید سه خروجی تولید کنید:\\n\\n"
    "1. کد پایتون کامل برای رسم نمودار مدار با matplotlib\\n"
    "2. کد SPICE netlist برای شبیه‌سازی\\n"
    "3. لیست JSON المان‌های مدار\\n\\n"
    "کد پایتون شما باید:\\n"
    "- از matplotlib و matplotlib.patches استفاده کند\\n"
    "- یک تابع اصلی به نام `draw_circuit(ax)` داشته باشد که یک matplotlib axes را به عنوان ورودی می‌گیرد\\n"
    "- المان‌های مدار را به درستی رسم کند (مقاومت، خازن، سلف، منبع ولتاژ، منبع جریان، دیود، ترانزیستور، op-amp و غیره)\\n"
    "- سیم‌ها و اتصالات را رسم کند\\n"
    "- برچسب‌ها و مقادیر المان‌ها را نمایش دهد\\n\\n"
    "**کدهای دقیق برای رسم المان‌ها (باید از این کدها استفاده کنید):**\\n\\n"
    "**1. مقاومت (Resistor):**\\n"
    "```python\\n"
    "def draw_resistor(ax, x, y, width=0.6, height=0.2, label='R', value=''):\\n"
    "    # رسم خط زیگزاگ مقاومت\\n"
    "    zigzag_x = [x, x+width*0.2, x+width*0.2, x+width*0.4, x+width*0.4, x+width*0.6, x+width*0.6, x+width*0.8, x+width*0.8, x+width]\\n"
    "    zigzag_y = [y+height/2, y+height/2, y+height, y+height, y, y, y+height, y+height, y+height/2, y+height/2]\\n"
    "    ax.plot(zigzag_x, zigzag_y, 'k-', linewidth=2)\\n"
    "    # خطوط اتصال\\n"
    "    ax.plot([x-0.2, x], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"
    "    ax.plot([x+width, x+width+0.2], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"
    "    # برچسب\\n"
    "    if value:\\n"
    "        ax.text(x+width/2, y+height+0.15, f'{label}\\\\n{value}', fontsize=9, ha='center', va='bottom')\\n"
    "    else:\\n"
    "        ax.text(x+width/2, y+height+0.15, label, fontsize=9, ha='center', va='bottom')\\n"
    "```\\n\\n"
    "**2. دیود (Diode):**\\n"
    "```python\\n"
    "def draw_diode(ax, x, y, width=0.4, height=0.3, label='D', value='', reverse=False):\\n"
    "    # مثلث دیود\\n"
    "    if reverse:\\n"
    "        triangle = patches.Polygon([(x, y), (x, y+height), (x+width*0.6, y+height/2)], \\n"
    "                                   closed=True, edgecolor='black', facecolor='white', linewidth=2)\\n"
    "        bar_x = x - width*0.2\\n"
    "    else:\\n"
    "        triangle = patches.Polygon([(x, y+height/2), (x+width*0.6, y), (x+width*0.6, y+height)], \\n"
    "                                   closed=True, edgecolor='black', facecolor='white', linewidth=2)\\n"
    "        bar_x = x + width*0.6\\n"
    "    ax.add_patch(triangle)\\n"\
    "    # خط عمودی (کاتد)\\n"\
    "    ax.plot([bar_x, bar_x], [y, y+height], 'k-', linewidth=2)\\n"\
    "    # خطوط اتصال\\n"\
    "    if reverse:\\n"\
    "        ax.plot([x-0.2, x], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"\
    "        ax.plot([bar_x, bar_x-0.2], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"\
    "    else:\\n"\
    "        ax.plot([x-0.2, x], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"\
    "        ax.plot([bar_x, bar_x+0.2], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"\
    "    # برچسب\\n"\
    "    if value:\\n"
    "        ax.text(x+width/2, y+height+0.15, f'{label}\\\\n{value}', fontsize=9, ha='center', va='bottom')\\n"
    "    else:\\n"
    "        ax.text(x+width/2, y+height+0.15, label, fontsize=9, ha='center', va='bottom')\\n"
    "```\\n\\n"
    "**3. ترانزیستور NPN (BJT NPN):**\\n"
    "```python\\n"
    "def draw_transistor_npn(ax, x, y, size=0.4, label='Q', value=''):\\n"
    "    # دایره ترانزیستور\\n"
    "    circle = patches.Circle((x, y), size, fill=False, edgecolor='black', linewidth=2)\\n"
    "    ax.add_patch(circle)\\n"
    "    # خط عمودی مرکزی\\n"
    "    ax.plot([x, x], [y-size, y+size], 'k-', linewidth=2)\\n"
    "    # پایه Base (چپ)\\n"
    "    ax.plot([x-size, x], [y, y], 'k-', linewidth=2)\\n"
    "    ax.text(x-size-0.15, y, 'B', fontsize=8, ha='right', va='center')\\n"
    "    # پایه Collector (بالا راست)\\n"
    "    collector_x = x + size * 0.707\\n"
    "    collector_y = y - size * 0.707\\n"
    "    ax.plot([x, collector_x], [y-size, collector_y], 'k-', linewidth=2)\\n"
    "    ax.plot([collector_x, collector_x+0.2], [collector_y, collector_y], 'k-', linewidth=2)\\n"
    "    ax.text(collector_x+0.25, collector_y, 'C', fontsize=8, ha='left', va='center')\\n"
    "    # پایه Emitter (پایین راست) با فلش\\n"
    "    emitter_x = x + size * 0.707\\n"
    "    emitter_y = y + size * 0.707\\n"
    "    ax.plot([x, emitter_x], [y+size, emitter_y], 'k-', linewidth=2)\\n"
    "    ax.plot([emitter_x, emitter_x+0.2], [emitter_y, emitter_y], 'k-', linewidth=2)\\n"
    "    # فلش روی Emitter\\n"
    "    arrow = patches.FancyArrowPatch((emitter_x+0.1, emitter_y), (emitter_x+0.2, emitter_y),\\n"
    "                                   arrowstyle='->', mutation_scale=15, linewidth=2, color='black')\\n"
    "    ax.add_patch(arrow)\\n"
    "    ax.text(emitter_x+0.25, emitter_y, 'E', fontsize=8, ha='left', va='center')\\n"
    "    # برچسب\\n"
    "    if value:\\n"
    "        ax.text(x, y-size-0.2, f'{label}\\\\n{value}', fontsize=9, ha='center', va='top')\\n"
    "    else:\\n"
    "        ax.text(x, y-size-0.2, label, fontsize=9, ha='center', va='top')\\n"
    "```\\n\\n"
    "**4. مولد ولتاژ DC (Voltage Source):**\\n"
    "```python\\n"
    "def draw_voltage_source(ax, x, y, width=0.3, height=0.4, label='V', value='', reverse=False):\\n"
    "    # خط بلند (مثبت)\\n"
    "    long_line_y = y + height*0.3 if reverse else y\\n"
    "    ax.plot([x, x], [long_line_y, long_line_y+height*0.4], 'k-', linewidth=3)\\n"
    "    # خط کوتاه (منفی)\\n"
    "    short_line_y = y if reverse else y + height*0.3\\n"
    "    ax.plot([x, x], [short_line_y, short_line_y+height*0.2], 'k-', linewidth=3)\\n"
    "    # خطوط اتصال\\n"
    "    ax.plot([x-0.2, x], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"
    "    ax.plot([x, x+0.2], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"
    "    # علامت + و -\\n"
    "    if not reverse:\\n"
    "        ax.text(x-0.1, long_line_y+height*0.2, '+', fontsize=12, ha='center', va='center', weight='bold')\\n"
    "        ax.text(x-0.1, short_line_y+height*0.1, '-', fontsize=12, ha='center', va='center', weight='bold')\\n"
    "    else:\\n"
    "        ax.text(x-0.1, long_line_y+height*0.2, '-', fontsize=12, ha='center', va='center', weight='bold')\\n"
    "        ax.text(x-0.1, short_line_y+height*0.1, '+', fontsize=12, ha='center', va='center', weight='bold')\\n"
    "    # برچسب\\n"
    "    if value:\\n"
    "        ax.text(x+0.25, y+height/2, f'{label}\\\\n{value}', fontsize=9, ha='left', va='center')\\n"
    "    else:\\n"
    "        ax.text(x+0.25, y+height/2, label, fontsize=9, ha='left', va='center')\\n"
    "```\\n\\n"
    "**5. خازن (Capacitor):**\\n"
    "```python\\n"
    "def draw_capacitor(ax, x, y, width=0.2, height=0.4, label='C', value=''):\\n"
    "    # دو خط عمودی موازی\\n"
    "    gap = width * 0.3\\n"
    "    ax.plot([x-gap/2, x-gap/2], [y, y+height], 'k-', linewidth=3)\\n"
    "    ax.plot([x+gap/2, x+gap/2], [y, y+height], 'k-', linewidth=3)\\n"
    "    # خطوط اتصال\\n"
    "    ax.plot([x-0.2, x-gap/2], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"
    "    ax.plot([x+gap/2, x+0.2], [y+height/2, y+height/2], 'k-', linewidth=2)\\n"
    "    # برچسب\\n"
    "    if value:\\n"
    "        ax.text(x, y+height+0.15, f'{label}\\\\n{value}', fontsize=9, ha='center', va='bottom')\\n"
    "    else:\\n"
    "        ax.text(x, y+height+0.15, label, fontsize=9, ha='center', va='bottom')\\n"
    "```\\n\\n"
    "**مهم: هنگام رسم مدار، حتماً از توابع بالا استفاده کنید. فاصله بین المان‌ها را زیاد کنید (حداقل 1.5 واحد بین مراکز المان‌ها).**\\n\\n"
    "فرمت پاسخ:\\n"
    "شما باید پاسخ خود را به صورت یک JSON object برگردانید با فیلدهای زیر:\\n"
    "{\\n"
    '  "pythonCode": "کد پایتون در بلوک ```python",\\n'\
    '  "spice": "کد SPICE netlist کامل",\\n'\
    '  "components": [{"ref": "R1", "type": "R", "value": "1k", "nodes": ["n1", "n2"]}, ...]\\n'\
    "}\\n\\n"
    "مثال کد پایتون کامل:\\n"
    "```python\\n"
    "import matplotlib.pyplot as plt\\n"
    "import matplotlib.patches as patches\\n"
    "import numpy as np\\n\\n"
    "# تعریف توابع رسم المان‌ها (از کدهای بالا استفاده کنید)\\n\\n"
    "def draw_circuit(ax):\\n"
    "    # رسم المان‌ها با استفاده از توابع تعریف شده\\n"
    "    # مثال: draw_resistor(ax, x=1, y=1, label='R1', value='1k')\\n"
    "    # مثال: draw_diode(ax, x=2.5, y=1, label='D1')\\n"
    "    # مثال: draw_transistor_npn(ax, x=4, y=1, label='Q1')\\n"
    "    # مثال: draw_voltage_source(ax, x=0, y=1, label='V1', value='5V')\\n"
    "    # مثال: draw_capacitor(ax, x=5.5, y=1, label='C1', value='10uF')\\n"
    "    \\n"
    "    # اتصال المان‌ها با خطوط\\n"
    "    # ax.plot([x1, x2], [y1, y2], 'k-', linewidth=2)\\n"
    "    \\n"
    "    ax.set_aspect('equal')\\n"
    "    ax.axis('off')\\n"
    "    ax.set_xlim(-1, 10)\\n"
    "    ax.set_ylim(-1, 3)\\n"
    "```\\n\\n"
    "مثال SPICE:\\n"
    ".title Circuit Description\\n"
    "V1 n1 0 5\\n"
    "R1 n1 n2 1k\\n"
    ".end\\n\\n"
    "مهم: اگر نمی‌توانید JSON تولید کنید، حداقل کد پایتون را در بلوک ```python برگردانید.\\n"
    "کد پایتون باید کامل و قابل اجرا باشد و یک تابع `draw_circuit(ax)` داشته باشد.\\n"
    "حتماً از توابع رسم المان‌های بالا استفاده کنید و فاصله بین المان‌ها را زیاد کنید.\\n"
